apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one
data:
  index.html: |
    <html>
      <head>
        <title>app-one</title>
      </head>
      <body>
        <h1>hello world from <span color="purple">app-one</span>!</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-file
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: static-file
        configMap:
          name: app-one
---
apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  selector:
    app: app-one
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
