LOGIN = "ecaceres"

MASTER_NAME = "#{LOGIN}S"
MASTER_IP = "192.168.56.110"

Vagrant.configure(2) do |config|
    config.vm.box = "hashicorp/bionic64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 4048
        v.cpus = 4
    end

    config.vm.define MASTER_NAME do |control|
        control.vm.hostname = MASTER_NAME
        control.vm.network "private_network", ip: MASTER_IP

        control.vm.provider "virtualbox" do |v|
            v.name = MASTER_NAME
        end
        
        control.vm.provision "docker"
        control.vm.provision "shell", args: [MASTER_IP], inline: <<-SHELL
            . /vagrant/scripts/install.sh $1
            . /vagrant/scripts/deploy.sh
        SHELL
    end
end
