version: "3.9"
services:
  database:
    build: services/database
    expose:
      - 3306
    volumes:
      - ./data/database:/data
    init: true
    restart: always
    environment:
      - WORDPRESS_DATABASE_PASSWORD
      - PHPMYADMIN_DATABASE_PASSWORD
  phpmyadmin:
    build: services/phpmyadmin
    expose:
      - 80
    init: true
    depends_on:
      - database
    restart: always
    environment:
      - WORDPRESS_DATABASE_PASSWORD
      - PHPMYADMIN_DATABASE_PASSWORD
  wordpress:
    build: services/wordpress
    expose:
      - 80
    volumes:
      - ./data/wordpress:/data
    init: true
    depends_on:
      - database
    restart: always
    environment:
      - "DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}"
  gateway:
    build: services/gateway
    ports:
      - "80:80"
      - "443:443"
    init: true
    depends_on:
      - phpmyadmin
      - wordpress
    restart: always
