version: "3.9"
services:
  database:
    build: services/database
    expose:
      - 3306
    volumes:
      - database:/data
    init: true
    restart: always
  phpmyadmin:
    build: services/phpmyadmin
    expose:
      - 80
    init: true
    depends_on:
      - database
    restart: always
  wordpress:
    build: services/wordpress
    expose:
      - 80
    init: true
    depends_on:
      - database
    restart: always
  gateway:
    build: services/gateway
    ports:
      - "80:80"
      - "443:443"
    init: true
    depends_on:
      - phpmyadmin
      - wordpress
    restart: always
volumes:
  database: {}
