version: "3.9"
services:
  database:
    build: services/database
    expose:
      - 3306
    volumes:
      - database:/data
    init: true
  phpmyadmin:
    build: services/phpmyadmin
    ports:
      - "80:80"
    init: true
volumes:
  database: {}
