LOGIN = "ecaceres"

MASTER_NAME = "#{LOGIN}S"
MASTER_IP = "192.168.56.110"

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 12288
        v.cpus = 8
    end

    config.vm.define MASTER_NAME do |control|
        control.vm.hostname = MASTER_NAME
        control.vm.network "private_network", ip: MASTER_IP
        control.vm.network "forwarded_port", guest: 8888, host: 8888

        control.vm.provider "virtualbox" do |v|
            v.name = MASTER_NAME
        end
    end
end
