LOGIN = "ecaceres"

MASTER_NAME = "#{LOGIN}S"
MASTER_IP = "192.168.56.110"

WORKER_NAME = "#{LOGIN}SW"
WORKER_IP = "192.168.56.111"

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define MASTER_NAME do |control|
        control.vm.hostname = MASTER_NAME
        control.vm.network "private_network", ip: MASTER_IP

        control.vm.provider "virtualbox" do |v|
            v.name = MASTER_NAME
        end

        control.vm.provision "shell", path: "scripts/install-tools.sh", reset: true
        control.vm.provision "shell", args: [MASTER_IP], path: "scripts/install-master.sh"
    end

    config.vm.define WORKER_NAME do |control|
        control.vm.hostname = WORKER_NAME
        control.vm.network "private_network", ip: WORKER_IP

        control.vm.provider "virtualbox" do |v|
            v.name = WORKER_NAME
        end

        control.vm.provision "shell", path: "scripts/install-tools.sh", reset: true
        control.vm.provision "shell", args: [MASTER_IP, WORKER_IP], path: "scripts/install-worker.sh"
    end
end
